spring.application.name=PortoMaquinas

spring.datasource.url=jdbc:postgresql://localhost:5432/portoWebsite
spring.datasource.username=postgres
spring.datasource.password=anomalocaris

server.port=8081

spring.datasource.driver-class-name=org.postgresql.Driver